const fs=require('fs'),vm=require('vm'),assert=require('assert');
class El{constructor(){this.children=[];this.value='';this.textContent='';this.attributes={};this.dataset={};this.style={};this.classList={add:()=>{},remove:()=>{},contains:()=>false}}append(...x){this.children.push(...x)}replaceChildren(...x){this.children=x}setAttribute(k,v){this.attributes[k]=v}getAttribute(k){return this.attributes[k]}reset(){this.resetCalled=true}click(){this.onclick?.();this.listeners?.click?.()}addEventListener(k,fn){(this.listeners??={})[k]=fn}querySelector(){return this.button??=new El()}focus(){}}
function run(path,initial={}){const elements={};const storage={...initial};const document={querySelector:s=>elements[s]??=new El(),createElement:()=>new El(),querySelectorAll:()=>[],addEventListener:()=>{}};for(const s of ['#name','#city','#category','#source'])document.querySelector(s);document.querySelector('#filter').value='Tous';const ctx={document,localStorage:{getItem:k=>storage[k]??null,setItem:(k,v)=>storage[k]=v},console,alert:()=>{},confirm:()=>true,URL:{createObjectURL:()=>'',revokeObjectURL:()=>{}},Blob,Math,Date,setTimeout:()=>{},navigator:{clipboard:{writeText:async()=>{}}}};vm.createContext(ctx);const html=fs.readFileSync(path,'utf8');const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];vm.runInContext(script,ctx);return {elements,storage,ctx}}
{
 const {elements:e,storage,ctx}=run('partenaires.html');assert.equal(JSON.parse(storage['atlas-partners-v1']).length,11);e['#name'].value='Coopérative essai';e['#city'].value='Khénifra';e['#category'].value='Bois';e['#add'].onsubmit({preventDefault(){},target:new El()});assert.equal(JSON.parse(storage['atlas-partners-v1']).length,12);e['#search'].value='Coopérative essai';e['#search'].oninput();assert.equal(e['#list'].children.length,1);const item=e['#list'].children[0];const select=item.children.find(x=>x.onchange);select.value='Qualifiée';select.onchange();assert.equal(JSON.parse(storage['atlas-partners-v1']).at(-1).status,'Qualifiée');const again=run('partenaires.html',storage);assert.equal(JSON.parse(again.storage['atlas-partners-v1']).length,12);assert.equal(JSON.parse(again.storage['atlas-partners-v1']).at(-1).status,'Qualifiée');const csv=vm.runInContext('exportCsv()',ctx);assert.equal(vm.runInContext('importCsv(exportCsv()).added',ctx),0);const newCsv=csv+'\r\n"Atelier, essai","Fès","Bois","https://example.com","À vérifier","Ligne 1\nLigne 2"';assert.equal(vm.runInContext('importCsv('+JSON.stringify(newCsv)+').added',ctx),1);assert.equal(JSON.parse(storage['atlas-partners-v1']).length,13);assert.throws(()=>vm.runInContext('importCsv('+JSON.stringify(csv+'\r\n"Invalide","Fès","Bois","javascript:bad","À vérifier",""')+')',ctx));assert.equal(JSON.parse(storage['atlas-partners-v1']).length,13);console.log('Suivi : ajout, filtre, état, persistance et import/export CSV OK');
}
{
 const elements={};const storage={};const filters=['Tous','Tiroirs','Décoration'].map(x=>{const e=new El();e.dataset.filter=x;return e});const document={querySelector:s=>elements[s]??=new El(),querySelectorAll:s=>s==='.filter'?filters:[],createElement:()=>new El(),addEventListener:()=>{}};const ctx={document,localStorage:{getItem:k=>storage[k]??null,setItem:(k,v)=>storage[k]=v},navigator:{clipboard:{writeText:async()=>{}}},setTimeout:()=>{}};vm.createContext(ctx);const html=fs.readFileSync('index.html','utf8');vm.runInContext(html.match(/<script>([\s\S]*?)<\/script>/)[1],ctx);assert.equal(elements['#products'].children.length,3);elements['#search'].value='meuble';elements['#search'].oninput();assert.equal(elements['#products'].children.length,1);elements['#search'].value='';elements['#search'].oninput();elements['#products'].children[0].querySelector('button').click();assert.equal(elements['#count'].textContent,1);assert.equal(elements['#basketItems'].children.length,1);console.log('Vitrine : recherche, sélection et récapitulatif OK');
}
